name: Deploy API
on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  packages: write

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Convert repo name to lowercase
        run: echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push api container
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ env.REPO_NAME }}/api:latest
            ghcr.io/${{ env.REPO_NAME }}/api:${{ github.ref_name }}

      - name: Deploy api
        uses: deploys-app/deploys-action@v1
        with:
          project: ${{ secrets.DEPLOYS_PROJECT }}
          location: gke.cluster-rcf2
          name: ${{ secrets.DEPLOYS_DEPLOY_NAME_API }}
          image: ghcr.io/${{ env.REPO_NAME }}/api@${{ steps.docker_build.outputs.digest }}
        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
